---
session_name: default

windows:
  - window_name: notes
    panes:
      - start_directory: ~/Dropbox/notes

  - window_name: emacs
    panes:
      - start_directory: ~/emacsen/mine

  - focus: true
