#!/bin/zsh
# This hook is sourced after a new virtualenv is activated.

# Style checking:
pip install rope
pip install flake8
pip install autoflake
pip install pydocstyle
pip install pyls-mypy
pip install pyls-isort

pip install pyls-black
pip install yapf

pip install pydoc_utils
pip install importmagic epc

# lsp
pip install 'python-language-server[all]'
# For dap-mode debugging:
pip install debugpy

# Essential:
pip install ipython

# Nicer testing:
pip install pytest
pip install pytest-describe
pip install pytest-spec
pip install coverage

# For project bootstrap:
pip install -U cookiecutter
